"""
LLM Forge - Tester Module
Inference, Chat, Evaluation
"""
import random
import time
from typing import List, Dict, Generator
import os

# Mock responses for demo when model not loaded
MOCK_RESPONSES = [
    "That's a great question! Based on my fine-tuned knowledge, I can tell you that...",
    "Here's what I learned during training: The key insight is to focus on efficiency and performance.",
    "As an AI model trained with LLM Forge, I can generate high-quality responses quickly.",
    "Interesting! Let me break this down step by step for you.",
    "Based on the dataset you provided, the pattern shows that optimization is crucial for LLMs.",
]

def mock_generate(prompt: str, config: Dict = None) -> str:
    """Generate mock response for demo"""
    if not prompt:
        return "Please enter a prompt!"
    
    # Make it look somewhat relevant
    config = config or {}
    temp = config.get('temperature', 0.7)
    
    base = random.choice(MOCK_RESPONSES)
    
    # Add some variation based on prompt
    if "code" in prompt.lower() or "python" in prompt.lower():
        return f"Here's a Python example for your request:\n\n```python\n# Generated by LLM Forge\ndef efficient_function(prompt='{prompt[:20]}'):\n    print('Optimized for speed with QLoRA')\n    return 'Fast inference!'\n```\n\n{base}"
    elif "what" in prompt.lower() or "explain" in prompt.lower():
        return f"**Explanation for:** {prompt}\n\n{base}\n\nKey points:\n- Highly efficient with 4-bit quantization\n- Trained with LoRA rank {config.get('lora_r', 16)}\n- Optimized for your dataset"
    else:
        return f"{base}\n\nYou asked: \"{prompt}\"\n\nMy response is generated with temperature={temp} for {'creative' if temp>0.8 else 'focused'} output. In production, this would be your actual fine-tuned model!"

def generate_response(prompt: str, config: Dict = None, model_path: str = None) -> Generator[str, None, None]:
    """
    Generate response with streaming
    Tries real model if available, else mock
    """
    config = config or {}
    max_tokens = config.get('max_tokens', 150)
    
    try:
        # Try real inference if model exists
        if model_path and os.path.exists(model_path):
            # Real inference would go here
            # For demo, still use mock but streaming
            raise RuntimeError("Use mock for demo")
        
        # Mock streaming
        full_response = mock_generate(prompt, config)
        # Stream word by word
        words = full_response.split()
        current = ""
        for word in words:
            current += word + " "
            yield current
            time.sleep(0.05)
            
    except Exception as e:
        # Fallback
        yield mock_generate(prompt, config)

def batch_inference(prompts: List[str], config: Dict = None) -> List[Dict]:
    """Batch inference for CSV testing"""
    results = []
    for i, prompt in enumerate(prompts):
        if not prompt or not str(prompt).strip():
            continue
        response = mock_generate(str(prompt), config)
        results.append({
            "id": i+1,
            "prompt": str(prompt)[:100],
            "response": response[:200] + "...",
            "full_response": response,
            "tokens": len(response.split()),
            "time": f"{random.uniform(0.3, 1.2):.2f}s"
        })
    return results

def calculate_metrics(predictions: List[str], references: List[str] = None) -> Dict:
    """Calculate evaluation metrics - mocked for demo"""
    import random
    # In real app, use evaluate library
    metrics = {
        "perplexity": round(random.uniform(8.5, 25.3), 2),
        "rouge1": round(random.uniform(0.35, 0.72), 3),
        "rougeL": round(random.uniform(0.30, 0.68), 3),
        "bleu": round(random.uniform(0.25, 0.55), 3),
        "avg_latency": f"{random.uniform(0.4, 1.1):.2f}s",
        "tokens_per_sec": round(random.uniform(35, 85), 1)
    }
    
    if references:
        metrics["exact_match"] = round(random.uniform(0.15, 0.45), 3)
    
    return metrics

def generate_api_code(model_path: str = "./checkpoints") -> Dict[str, str]:
    python_code = f'''# Use your fine-tuned model via API
import requests

# FastAPI endpoint (from LLM Forge)
url = "http://localhost:8000/api/generate"
payload = {{
    "prompt": "Explain quantum computing",
    "temperature": 0.7,
    "max_tokens": 150,
    "top_p": 0.9
}}

response = requests.post(url, json=payload)
print(response.json()["response"])

# Or use directly with transformers
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

base_model = "Qwen/Qwen2-0.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(base_model)
model = AutoModelForCausalLM.from_pretrained(base_model, device_map="auto")
model = PeftModel.from_pretrained(model, "{model_path}")
model = model.merge_and_unload()

inputs = tokenizer("Hello, how are you?", return_tensors="pt")
outputs = model.generate(**inputs, max_new_tokens=100, temperature=0.7)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))
'''

    curl_code = f'''curl -X POST http://localhost:8000/api/generate \\
  -H "Content-Type: application/json" \\
  -d '{{
    "prompt": "Write a Python function to sort a list",
    "temperature": 0.7,
    "max_tokens": 200
  }}'
'''

    return {"python": python_code, "curl": curl_code}
